from setuptools import setup

setup(
    name='Flaskr',
    version='1.0',
    description='Experience Design project',
    packages=['flaskr'],
    zip_safe=False,
    install_requires=[
        'Click==7.0',
        'requests>=2.20.0',
        'numpy==1.15.4',
        'bezier==0.9.0',
        'python_resize_image==1.1.18',
        'Flask==1.0.2',
        'networkx==2.2',
        'Pillow==5.3.0',
        'ipykernel==4.5.0',
        'ipython==5.1.0',
        'ipython-genutils==0.1.0',
        'ipywidgets==5.2.2',
        'jsonschema==2.5.1',
        'matplotlib==3.0.1',
        'mistune==0.7.3',
        'nbconvert==4.2.0',
        'nbformat==4.1.0',
        'notebook>=5.7.2',
        'pandas==0.23.4',
        'prompt-toolkit==1.0.7',
        'ptyprocess==0.5.1',
        'pycparser==2.18,'
        'pyparsing==2.3.0',
        'python-dateutil==2.7.5',
        'scikit-learn==0.20.0',
        'scipy==1.1.0',
        'simplegeneric==0.8.1',
        'widgetsnbextension==1.2.6',
        'xlrd==1.1.0'
    ],
    include_package_data=True
)